### ISSUE TITLE
关于zeek/bro相关的插件和环境管理探讨

### ISSUE THREAD

**Issue by GTrunSec** [AlkenePan/awesome-bro#2]
最近我做了在NIXOS下的整体NSM和hunting env. https://github.com/hardenedlinux/NSM-data-analysis
至于我为什么选择NIX包来管理，主要是方便和包括版本控制。
我增加了julia R Haskell python等安全分析的环境，为zeek 和silk等元数据sensor 服务。

我一段时间基于org-mode 倒是做了类似awesome-bro相关的东西https://www.gtrun.org/custom/NsmOrg.html

但目前感觉这个东西主要是涉及到基础面的东西太多。Osquery我目前来说就是把相关安全测试，给迁移到pet snippet. 
你觉得类似项目，目前需要如何处理帮助他人。包括文档和插件的编写？

**Comment by AlkenePan** [comment]
我会把你的链接放在 `README.md` 中。
